// Cross-sections, taken from the geometry rather than from a picture of it.
//
// This is the bridge between a reference drawing and a model. A silhouette
// extracted from a render is a measurement of the renderer as much as of the
// model: it moves with the camera, the lens and the resolution. Slicing the
// mesh with a plane gives the same curve the model is actually made of, in
// millimetres, with nothing in between.
//
// It is also what makes symmetry answerable. Comparing triangle centroids
// across the centreline measures the *tessellation*, which legitimately differs
// side to side — the pillar surrounds are generated by walking the section in
// opposite directions. Comparing sections measures the *shape*.

import { round } from "./load.mjs";

/**
 * Intersect the model with the plane x = station.
 *
 * Returns closed loops where it can chain them, and open polylines where the
 * surface is genuinely open at that station (a section through a door aperture
 * is not a closed curve, and pretending otherwise would invent geometry).
 */
export function sliceAt(model, station, { weld_m = 0.0015, parts = null } = {}) {
  const wanted = parts ? new Set(parts) : null;
  const segments = [];

  for (const [name, entry] of model.parts) {
    if (wanted && !wanted.has(name)) continue;
    for (let i = entry.triangleStart; i < entry.triangleStart + entry.triangleCount; i += 1) {
      const t = model.triangles[i];
      const xs = [t[0], t[3], t[6]];
      const ys = [t[1], t[4], t[7]];
      const zs = [t[2], t[5], t[8]];
      const side = xs.map((x) => Math.sign(x - station));
      if (side[0] === side[1] && side[1] === side[2]) continue; // wholly one side

      const hits = [];
      for (let e = 0; e < 3; e += 1) {
        const a = e;
        const b = (e + 1) % 3;
        const xa = xs[a];
        const xb = xs[b];
        if ((xa < station && xb < station) || (xa > station && xb > station)) continue;
        if (xa === xb) continue;
        const k = (station - xa) / (xb - xa);
        if (k < 0 || k > 1) continue;
        hits.push([ys[a] + (ys[b] - ys[a]) * k, zs[a] + (zs[b] - zs[a]) * k]);
      }
      if (hits.length >= 2) segments.push([hits[0], hits[1]]);
    }
  }

  return { station: round(station), segments, ...chain(segments, weld_m) };
}

/** Chain segments end to end into loops and open runs. */
function chain(segments, weld) {
  const key = ([y, z]) => `${Math.round(y / weld)}:${Math.round(z / weld)}`;
  const ends = new Map();
  const used = new Array(segments.length).fill(false);
  segments.forEach(([a, b], i) => {
    for (const p of [a, b]) {
      const k = key(p);
      if (!ends.has(k)) ends.set(k, []);
      ends.get(k).push(i);
    }
  });

  const loops = [];
  const open = [];
  const same = (a, b) => key(a) === key(b);

  for (let i = 0; i < segments.length; i += 1) {
    if (used[i]) continue;
    used[i] = true;
    const path = [segments[i][0], segments[i][1]];
    let grew = true;
    while (grew) {
      grew = false;
      for (const endIndex of [0, path.length - 1]) {
        const tip = path[endIndex];
        for (const j of ends.get(key(tip)) ?? []) {
          if (used[j]) continue;
          const [a, b] = segments[j];
          const next = same(a, tip) ? b : same(b, tip) ? a : null;
          if (!next) continue;
          used[j] = true;
          if (endIndex === 0) path.unshift(next);
          else path.push(next);
          grew = true;
          break;
        }
        if (grew) break;
      }
    }
    const closed = path.length > 3 && same(path[0], path[path.length - 1]);
    (closed ? loops : open).push(path.map(([y, z]) => [round(y, 5), round(z, 5)]));
  }

  return {
    loops,
    openRuns: open,
    closed: loops.length,
    // An open run at a station that should be closed is a hole, or a section
    // taken through an aperture. Either way it is worth knowing about.
    openCount: open.length,
  };
}

/** The z extent of a section at a given height band — the width, exactly. */
export function widthAt(model, station, { yMin = -Infinity, yMax = Infinity } = {}) {
  const { segments } = sliceAt(model, station);
  let min = Infinity;
  let max = -Infinity;
  for (const [a, b] of segments) {
    for (const [y, z] of [a, b]) {
      if (y < yMin || y > yMax) continue;
      if (z < min) min = z;
      if (z > max) max = z;
    }
  }
  if (min === Infinity) return null;
  return { station: round(station), zMin: round(min), zMax: round(max), width_m: round(max - min) };
}

/**
 * Symmetry of the SHAPE, measured section by section.
 *
 * For each station, compare the outline's left half with its mirrored right
 * half at a ladder of heights. This is immune to the two sides being
 * tessellated differently, which they are.
 */
export function sectionSymmetry(model, { stations = 41, heights = 33, tolerance_m = 0.002 } = {}) {
  const { min, max } = model.bounds;
  const rows = [];
  let worst = { deviation_m: 0 };

  for (let i = 0; i < stations; i += 1) {
    const x = min.x + ((max.x - min.x) * (i + 0.5)) / stations;
    const { segments } = sliceAt(model, x);
    if (!segments.length) continue;

    for (let h = 0; h < heights; h += 1) {
      const y = min.y + ((max.y - min.y) * (h + 0.5)) / heights;
      let left = -Infinity;
      let right = Infinity;
      for (const [a, b] of segments) {
        // Where this segment crosses height y, take its z.
        const [ya, za] = a;
        const [yb, zb] = b;
        if ((ya < y && yb < y) || (ya > y && yb > y)) continue;
        if (ya === yb) continue;
        const k = (y - ya) / (yb - ya);
        const z = za + (zb - za) * k;
        if (z > left) left = z;
        if (z < right) right = z;
      }
      if (left === -Infinity || right === Infinity) continue;
      const deviation = Math.abs(left + right); // perfect symmetry -> right == -left
      rows.push({ x: round(x), y: round(y), deviation_m: round(deviation, 5) });
      if (deviation > worst.deviation_m) worst = { x: round(x), y: round(y), deviation_m: round(deviation, 5) };
    }
  }

  const within = rows.filter((r) => r.deviation_m <= tolerance_m).length;
  const mean = rows.length ? rows.reduce((sum, r) => sum + r.deviation_m, 0) / rows.length : 0;
  return {
    tolerance_mm: round(tolerance_m * 1000, 1),
    samples: rows.length,
    withinTolerance: within,
    symmetric_fraction: rows.length ? round(within / rows.length, 4) : 1,
    meanDeviation_mm: round(mean * 1000, 2),
    worst: { ...worst, deviation_mm: round(worst.deviation_m * 1000, 2) },
  };
}
